Feature/clubhouse
abdulkhaliqdev/clubhouse pull request #1
Opened 2021-02-25 20:04 UTC by abdulkhaliqdev

2021-02-26 04:01 UTC, voscarmv requested changes
Impressive work. 💻 👀 ✨ 

- Your project works smoothly.
- The site is fully featured and it all works as it should.

## However, there are some changes required 👀 🧰 🔨 🔧 

- I only noticed a couple of details with your code. I've detailed them in the code comments. Please check them out and apply the changes requested there.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-02-26 04:01 UTC, voscarmv commented on config/routes.rb
> +  resources :posts
Please change this to 
```
resources :posts, only: [:new, :create, :index]
```

2021-02-26 04:01 UTC, voscarmv commented on app/controllers/posts_controller.rb
> +  end
Please use `@post = Post.new` for this action.

2021-02-26 04:01 UTC, voscarmv commented on app/views/posts/_feed.html.erb
> +</div>
Instead of using `if` logic in your views, move it to helper functions.

2021-02-27 08:45 UTC, mke2111 approved these changes
# **🎉 STATUS: APPROVED 🎉** 

## Hey @abdulkhaliqdev & @jadx2, 👋🏽 
 **Congratulations 🥳 🥂 . The clubhouse secrets work just fine and look user-friendly.**

I'm approving this PR but there is one mandatory change to make.

- [ ] In your readme file, Kindly add `rails db:migrate` to your usage section before starting the server.

### Make the requested change and then proceed.
**You may now merge to the develop branch and submit a project completion form. 👍🏽** 

## Cheers!! 🍹 

## Reach me on slack for a chitchat 🆘  **Roy Mukuye**

2021-03-01 15:04 UTC, merged